// Generated by CoffeeScript 1.3.3
(function() {
  var DoccoRunner, child_process;

  child_process = require('child_process');

  module.exports = DoccoRunner = (function() {

    DoccoRunner.prototype.brunchPlugin = true;

    DoccoRunner.prototype.type = 'javascript';

    DoccoRunner.prototype.extension = 'js';

    DoccoRunner.prototype.pattern = /src\/.+\.(js|coffee|litcoffee)/;

    function DoccoRunner(config) {
      this.config = config;
    }

    DoccoRunner.prototype.compile = function(params, callback) {
      var command, execPath;
      execPath = 'node_modules/docco-brunch/node_modules/docco/bin/docco';
      command = "" + execPath + " " + params.path;
      child_process.exec(command, function(error, stdout, stderr) {
        if (error != null) {
          return console.log("exec error: " + error);
        }
      });
      return callback(null, params);
    };

    return DoccoRunner;

  })();

}).call(this);
